"""
API Schemas Package

Intelligent API schemas with constraint-aware validation,
semantic understanding, and distributed orchestration support.
"""

from api.schemas.base import (
    BaseSchema,
    ConstraintType,
    ConstraintScope,
    Constraint,
    ConstraintGroup,
    SemanticRequest,
    RequestPriority,
    RetryPolicy,
    TimeoutConfig,
)
from api.schemas.dataset import (
    DataModality,
    DatasetFormat,
    QualityLevel,
    DatasetType,
    QualityConstraints,
    DataConstraints,
    SyntheticDataConfig,
    DatasetMetadata,
    DatasetConfig,
    DatasetGenerationRequest,
    DatasetExportRequest,
    DatasetFilter,
)
from api.schemas.workflow import (
    OrchestrationMode,
    ExecutionStrategy,
    StepStatus,
    StepType,
    StepDependency,
    StepResourceAllocation,
    WorkflowStep,
    WorkflowConfig,
    WorkflowPlan,
    WorkflowExecution,
    WorkflowTemplate,
    WorkflowSearch,
)
from api.schemas.orchestration import (
    TaskStatus,
    TaskPriority,
    TaskNode,
    TaskGraph,
    GPUAllocation,
    ProviderRouting,
    DistributedExecution,
    OrchestrationRequest,
    ExecutionMetrics,
    WorkerState,
    ShardingConfig,
)
from api.schemas.multimodal import (
    ModalityType as MultimodalModality,
    ProcessingPriority,
    MultimodalInput,
    ImageConfig,
    VideoConfig,
    AudioConfig,
    OCRConfig,
    PDFConfig,
    CodeConfig,
    TableConfig,
    ProcessingConfig,
    MultimodalFusion,
    ModalityRequirements,
    MultimodalRequest,
    ProcessingResult,
    ModalityCapability,
)
from api.schemas.validation import (
    ValidationStatus,
    ValidationSeverity,
    FeasibilityLevel,
    ConflictDetection,
    OptimizationSuggestion,
    ConstraintAnalysis,
    FeasibilityResult,
    ValidationIssue,
    ValidationResult,
    SemanticAnalysis,
    CostAnalysis,
    ResourceAnalysis,
    ScalabilityAssessment,
    ValidationSummary,
)
from api.schemas.planning import (
    PlanStatus,
    PlanStep,
    ExecutionPlan,
    CostEstimate,
    StorageEstimate,
    TimeEstimate,
    ResourceAllocation as PlanningResourceAllocation,
    ProviderRecommendation,
    PlanOptimization,
    WorkflowOptimization,
)
from api.schemas.jobs import (
    JobStatus,
    JobEvent,
    WebhookEvent,
    WebhookConfig,
    JobProgress,
    JobResult,
    JobCancellation,
    JobQuery,
    JobEventLog,
    JobMetadata,
    JobSummary,
)
from api.schemas.providers import (
    ProviderConstraint,
    ModelConstraint,
    CostBudget,
    RoutingPolicy,
    ModelSelection,
    ProviderMetrics,
    ProviderHealth,
    ProviderConfigUpdate,
)
from api.schemas.security import (
    RBACPermission,
    RoleType,
    UserContext,
    TenantContext,
    RateLimitConfig,
    SecurityPolicy,
    AuditLogEntry,
    APIKey,
    PolicyEvaluation,
)
from api.schemas.response import (
    ResponseStatus,
    ErrorCode,
    ValidationError,
    ErrorDetail,
    ErrorResponse,
    WarningDetail,
    PaginationMeta,
    MetaInfo,
    APIResponse,
    SuccessResponse,
    HealthResponse,
    StatusResponse,
    BatchResponse,
    StreamResponse,
)

# Import additional modules that server.py expects
from api.validation.engine import ConstraintReasoningEngine, SemanticValidator
from api.planning.planner import WorkflowPlanner
from api.execution.executor import AsyncJobExecutor, ProgressTracker
from api.observability.metrics import APIMetrics, ValidationMetrics

# Note: CheckpointResponse, RestoreCheckpointResponse, ProviderSwitchResponse,
# FailoverResponse, FailoverHistoryResponse and other response classes are in
# api/schemas.py (module). Import them directly in server.py to avoid circular imports.

__all__ = [
    # Base Schemas
    "BaseSchema",
    "ConstraintType",
    "ConstraintScope",
    "Constraint",
    "ConstraintGroup",
    "SemanticRequest",
    "RequestPriority",
    "RetryPolicy",
    "TimeoutConfig",

    # Dataset Schemas
    "DataModality",
    "DatasetFormat",
    "QualityLevel",
    "DatasetType",
    "QualityConstraints",
    "DataConstraints",
    "SyntheticDataConfig",
    "DatasetMetadata",
    "DatasetConfig",
    "DatasetGenerationRequest",
    "DatasetExportRequest",
    "DatasetFilter",

    # Workflow Schemas
    "OrchestrationMode",
    "ExecutionStrategy",
    "StepStatus",
    "StepType",
    "StepDependency",
    "StepResourceAllocation",
    "WorkflowStep",
    "WorkflowConfig",
    "WorkflowPlan",
    "WorkflowExecution",
    "WorkflowTemplate",
    "WorkflowSearch",

    # Orchestration Schemas
    "TaskStatus",
    "TaskPriority",
    "TaskNode",
    "TaskGraph",
    "GPUAllocation",
    "ProviderRouting",
    "DistributedExecution",
    "OrchestrationRequest",
    "ExecutionMetrics",
    "WorkerState",
    "ShardingConfig",

    # Multimodal Schemas
    "MultimodalModality",
    "ProcessingPriority",
    "MultimodalInput",
    "ImageConfig",
    "VideoConfig",
    "AudioConfig",
    "OCRConfig",
    "PDFConfig",
    "CodeConfig",
    "TableConfig",
    "ProcessingConfig",
    "MultimodalFusion",
    "ModalityRequirements",
    "MultimodalRequest",
    "ProcessingResult",
    "ModalityCapability",

    # Validation Schemas
    "ValidationStatus",
    "ValidationSeverity",
    "FeasibilityLevel",
    "ConflictDetection",
    "OptimizationSuggestion",
    "ConstraintAnalysis",
    "FeasibilityResult",
    "ValidationIssue",
    "ValidationResult",
    "SemanticAnalysis",
    "CostAnalysis",
    "ResourceAnalysis",
    "ScalabilityAssessment",
    "ValidationSummary",

    # Planning Schemas
    "PlanStatus",
    "PlanStep",
    "ExecutionPlan",
    "CostEstimate",
    "StorageEstimate",
    "PlanningResourceAllocation",
    "ProviderRecommendation",
    "PlanOptimization",
    "WorkflowOptimization",

    # Job Schemas
    "JobStatus",
    "JobEvent",
    "WebhookEvent",
    "WebhookConfig",
    "JobProgress",
    "JobResult",
    "JobCancellation",
    "JobQuery",
    "JobEventLog",
    "JobMetadata",
    "JobSummary",

    # Provider Schemas
    "ProviderConstraint",
    "ModelConstraint",
    "CostBudget",
    "RoutingPolicy",
    "ModelSelection",
    "ProviderMetrics",
    "ProviderHealth",
    "ProviderConfigUpdate",

    # Security Schemas
    "RBACPermission",
    "RoleType",
    "UserContext",
    "TenantContext",
    "RateLimitConfig",
    "SecurityPolicy",
    "AuditLogEntry",
    "APIKey",
    "PolicyEvaluation",

    # Response Schemas
    "ResponseStatus",
    "ErrorCode",
    "ValidationError",
    "ErrorDetail",
    "ErrorResponse",
    "WarningDetail",
    "PaginationMeta",
    "MetaInfo",
    "APIResponse",
    "SuccessResponse",
    "HealthResponse",
    "StatusResponse",
    "BatchResponse",
    "StreamResponse",

    # Additional modules
    "ConstraintReasoningEngine",
    "SemanticValidator",
    "WorkflowPlanner",
    "AsyncJobExecutor",
    "ProgressTracker",
    "APIMetrics",
    "ValidationMetrics",

    # From api/schemas.py
    "CheckpointResponse",
    "RestoreCheckpointResponse",
    "ProviderSwitchResponse",
    "FailoverResponse",
    "FailoverHistoryResponse",
    "ProviderTestRequest",
    "ProviderTestResponse",
    "ReportResponse",
    "ResearchRequest",
    "ResearchResponse",
    "AdaptabilityRequest",
    "AdaptabilityResponse",
    "JobRequest",
    "JobResponse",
    "JobDetailResponse",
]